name: Build AX6 ImmortalWrt (Mihomo)

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo docker image prune --all --force
        sudo -E apt-get update
        sudo -E apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt-get autoremove --purge -y
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"

    - name: Clone Source Code
      run: git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update & Install Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt
        echo 'CONFIG_TARGET_qualcommax=y' >> .config
        echo 'CONFIG_TARGET_qualcommax_ipq807x=y' >> .config
        echo 'CONFIG_TARGET_qualcommax_ipq807x_DEVICE_redmi_ax6-stock=y' >> .config
        make defconfig

    - name: Download Package
      run: |
        cd openwrt
        make download -j8

    - name: Compile the Firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Organize Files
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware Release
      uses: softprops/action-gh-release@v1
      if: steps.organize.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: AX6-Mihomo-Build-${{ github.run_id }}
        files: ${{ env.FIRMWARE }}/*
